#!/bin/bash

export PACKAGE_CORE_NAME="navidrome"
export PACKAGE_CORE_BIN_NAME="$PACKAGE_CORE_NAME"
export PACKAGE_CORE_VERSION=v0.48.0
export PACKAGE_CORE_RELEASE_DOWNLOAD="https://github.com/navidrome/navidrome/releases/download"
